Repository swaggo/swag, pull requests merged in 2019-07, with the labels that each got.

#426 add option to explicitly include or exclude third party dependencies
  README.md
  cmd/swag/main.go
  gen/gen.go
  parser.go
Labels: feature

#434 fix: fail when searchDir contains no package
  parser.go
  parser_test.go
  testdata/fixes-432/a/a.go
  testdata/fixes-432/b/b.go
  testdata/fixes-432/cmd/main.go
Labels: bug

#438 feat: ability to set "schemes" programatically
  README.md
  gen/gen.go
Labels: feature

#439 fix: only execute 'go list' when enable 'parseDependency' flag
  example/basic/api/api.go
  parser.go
  parser_test.go
  testdata/pare_outside_dependencies/cmd/main.go
Labels: enhancement

#452 Support @x- attributes for operations
  README.md
  operation.go
  operation_test.go
  testdata/simple2/docs/docs.go
  testdata/simple3/docs/docs.go
Labels: feature

#462 fix: support anonymous nested structure slice parsing
  parser.go
  parser_test.go
  property.go
  property_test.go
Labels: enhancement
