Repository swaggo/swag, pull requests merged in 2019-03, with the labels that each got.

#325 feat: add output flag to specify output dir
  README.md
  cmd/swag/main.go
  gen/gen.go
  gen/gen_test.go
Labels: feature

#333 use Immediate set in Makefile
  Makefile
Labels: enhancement

#336 fix govet error
  .travis.yml
  Makefile
  operation_test.go
Labels: enhancement

#345 chore: update gin-swagger examples and doc
  README.md
  assets/swagger-image.png
  example/celler/main.go
  go.mod
  go.sum
Labels: enhancement

#343 Initialize regexp.MustCompile only once
  operation.go
Labels: enhancement

#341 Fix handling of multiline description blocks
  parser.go
  parser_test.go
  testdata/single_file_api/main.go
Labels: bug

#350 refactor: return error instead of panic
  parser.go
Labels: enhancement

#354 refactor parseAndExtractionParamAttribute
  operation.go
Labels: enhancement

#353 use trim spaced string
  operation.go
Labels: enhancement

#355 refactor(parser): using error instead of panic
  parser.go
Labels: enhancement
