Repository swaggo/swag, pull requests merged in 2019-12, with the labels that each got.

#571 chore(CI): add GitHub action
  .github/workflows/ci.yml
  Makefile
  testdata/pare_outside_dependencies/cmd/main.go
Labels: enhancement

#579 fix bug in array param in body
  operation.go
  operation_test.go
Labels: bug

#501 Add generated time flag
  cmd/swag/main.go
  gen/gen.go
  gen/gen_test.go
Labels: feature
